# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            8
            11
          mvn-toolchain-id: |
            jdk8
            jdk11
          cache: maven

      - run: ls -l ~/.m2
      - run: cat ~/.m2/toolchains.xml
      - run: cat ~/.m2/settings.xml
      - run: java -version
      - run: which java

      - name: Build Java 11 Module
        run:  ./mvnw -f java11/pom.xml install

      - name: Build Java 8 Module
        run:  ./mvnw install
